const contextValue = useMemo(() => ({
    user, setUser, isAuthenticated: !!user, isAdmin,
    adminEmail, adminPassword, adminPin, updateAdminCredentials,
    systemConfig, updateSystemConfig: (upd) => { setSystemConfig(p => ({...p, ...upd})); Object.entries(upd).forEach(([k, v]) => systemConfigService.update(k, v as boolean)); },
    siteSettings, updateSiteSettings: (s) => { setSiteSettings(p => ({...p, ...s})); siteSettingsService.update(s); addAuditLog('Site Meta Updated', 'Modified global site description/contact', 'broadcast'); },
    promotionPlans, updatePromotionPlanRate: (m, r) => setPromotionPlans(p => p.map(plan => plan.months === m ? {...plan, rate: r} : plan)),
    safeSpots, addSafeSpot: (s) => safeSpotService.create(s).then(() => fetchData()), deleteSafeSpot: (id) => safeSpotService.delete(id).then(() => fetchData()),
    exportDatabaseBackup: () => { const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify({ listings, allUsers, reviews, siteSettings }, null, 2)); const dlAnchorElem = document.createElement('a'); dlAnchorElem.setAttribute("href", dataStr); dlAnchorElem.setAttribute("download", `Sealify_DB_Backup_${Date.now()}.json`); dlAnchorElem.click(); toast.success("Database Backup Exported!"); },
    language, setLanguage, t, categories, subcategories,
    addCategory: (c) => { setCategories(prev => [...prev, c]); categoryService.create(c).then(() => fetchData()); },
    deleteCategory: (id) => { setCategories(p => p.filter(c => c.id !== id)); categoryService.delete(id).then(() => fetchData()); },
    updateCategory: (id, name) => { setCategories(p => p.map(c => c.id === id ? {...c, name} : c)); categoryService.update(id, { name }).then(() => fetchData()); },
    analytics, marketStats, login, signup, sendPhoneOtp: async () => Math.floor(100000 + Math.random() * 900000).toString(), verifyPhoneOtp: async () => true,
    adminLogin, logout, listings, allUsers, updateUser, addUser, deleteUser,
    bulkUpdateUsers: (ids, upd) => ids.forEach(id => updateUser(id, upd)), bulkDeleteUsers: (ids) => ids.forEach(id => deleteUser(id)),
    bulkUpdateListings: (ids, upd) => ids.forEach(id => updateListing(id, upd)), bulkDeleteListings: (ids) => ids.forEach(id => deleteListing(id)),
    savedListingIds, recentlyViewedIds, userInterests, addRecentlyViewed,
    toggleSaveListing: async (id) => { if (user) { const exists = savedListingIds.includes(id); await favoriteService.toggle(user.id, id, exists); setSavedListingIds(p => exists ? p.filter(i => i !== id) : [...p, id]); } },
    isSaved: (id) => savedListingIds.includes(id), filters, setFilters, resetFilters: () => setFilters({ searchQuery: '', category: 'All', minPrice: null, maxPrice: null, condition: 'All', location: '', sortBy: 'newest' }),
    activeCategory, setActiveCategory: (c) => setFilters(f => ({...f, category: c})),
    compareListingIds, toggleCompareListing: (id) => setCompareListingIds(p => p.includes(id) ? p.filter(i => i !== id) : p.length < 3 ? [...p, id] : p),
    isInCompare: (id) => compareListingIds.includes(id), clearCompare: () => setCompareListingIds([]),
    createListing, updateListing, deleteListing, markAsSold, toggleFeaturedListing: async (id) => updateListing(id, { featured: !listings.find(l => l.id === id)?.featured }), promoteListing: async (id, dur, plan) => updateListing(id, { featured: true, promotionPlanName: plan, promotionDurationMonths: dur }),
    conversations, sendMessage,
    notifications, markNotificationRead: (id) => notificationService.markRead(id).then(() => fetchData()),
    markAllNotificationsRead: () => Promise.all(notifications.map(n => notificationService.markRead(n.id))).then(() => fetchData()),
    clearNotification: (id) => notificationService.clear(id).then(() => fetchData()),
    addNotification, broadcastMassNotification, dispatchPromotionalEmailDigest,
    passwordRequests, submitPasswordRequest: (r) => passwordRequestService.create(r).then(() => fetchData()),
    processPasswordRequest: (id, s) => passwordRequestService.updateStatus(id, s).then(() => fetchData()),
    verificationRequests, submitVerificationRequest: (r) => verificationService.create(r).then(() => fetchData()),
    processVerificationRequest: (id, s) => verificationService.updateStatus(id, s).then(() => { addAuditLog('Verification Processed', `Request ID ${id} set to ${s}`, 'verification'); fetchData(); }),
    promotionPaymentRequests, submitPromotionPaymentRequest: (r) => promotionService.create(r).then(() => fetchData()),
    processPromotionPaymentRequest: (id, s) => promotionService.updateStatus(id, s).then(() => { addAuditLog('Finance Approval', `Promotion Payment ID ${id} ${s}`, 'finance'); fetchData(); }),
    announcements, addAnnouncement: (a) => announcementService.create(a).then(() => fetchData()), toggleAnnouncement: (id) => announcementService.delete(id).then(() => fetchData()), deleteAnnouncement: (id) => announcementService.delete(id).then(() => fetchData()),
    reports, submitReport: (r) => reportService.create(r).then(() => fetchData()), processReport: (id) => reportService.updateStatus(id, 'resolved').then(() => fetchData()),
    disputeCases, submitDisputeCase: (d) => disputeService.create(d).then(() => fetchData()),
    processDisputeCase: (id, s) => disputeService.updateStatus(id, s).then(() => { addAuditLog('Dispute Mediated', `Dispute ID ${id} set to ${s}`, 'dispute'); fetchData(); }),
    auditLogs, addAuditLog,
    recentDeals, sealDeal: (l, b, p) => recentDealsService.create({ item_title: l, price: p, location: user?.location || 'Ogbomoso', time: 'Just now' }).then(() => fetchData()),
    intrusionLogs, recordIntrusion: (e, m) => intrusionService.create({ attempted_email: e, media_status: m, timestamp: new Date().toISOString() }).then(() => { addAuditLog('Unauthorized Access Attempt', `Email: ${e} | Payload: ${m}`, 'intrusion'); fetchData(); }),
    searchAlerts, saveSearchAlert: (a) => searchAlertService.create({ ...a, user_id: user?.id }).then(() => fetchData()),
    deleteSearchAlert: (id) => searchAlertService.delete(id).then(() => fetchData()),
    reviews, addReview: (r) => reviewService.create(r).then(() => fetchData()), deleteReview: (id) => reviewService.delete(id).then(() => fetchData()),
    buyerRequests, createBuyerRequest: (r) => buyerRequestService.create(r).then(() => fetchData()), deleteBuyerRequest: (id) => buyerRequestService.delete(id).then(() => fetchData()),
    wallet, transactions, requestPayout: async (amount: number) => {
      if (!wallet || wallet.balance < amount) {
        toast.error('Insufficient balance');
        return;
      }
      setWallet(prev => prev ? { ...prev, balance: prev.balance - amount, pendingBalance: prev.pendingBalance + amount } : null);
      setTransactions(prev => [{ id: `txn_${Date.now()}`, walletId: wallet?.id || '', type: 'payout', amount: -amount, status: 'pending', description: 'Withdrawal to bank', createdAt: new Date().toISOString() }, ...prev]);
      toast.success(`Payout of ₦${amount.toLocaleString()} requested`);
    },
    loading, isSyncing, lastSyncTime, syncDatabase: fetchData, error
  }), [
    user, isAdmin, adminEmail, adminPassword, adminPin, systemConfig, siteSettings, promotionPlans, safeSpots,
    language, categories, subcategories, analytics, marketStats, login, signup, adminLogin, logout,
    listings, allUsers, updateUser, addUser, deleteUser, savedListingIds, recentlyViewedIds, userInterests,
    addRecentlyViewed, toggleSaveListing: async (id) => { if (user) { const exists = savedListingIds.includes(id); await favoriteService.toggle(user.id, id, exists); setSavedListingIds(p => exists ? p.filter(i => i !== id) : [...p, id]); } },
    isSaved: (id) => savedListingIds.includes(id), filters, setFilters, resetFilters: () => setFilters({ searchQuery: '', category: 'All', minPrice: null, maxPrice: null, condition: 'All', location: '', sortBy: 'newest' }),
    activeCategory, setActiveCategory: (c) => setFilters(f => ({...f, category: c})),
    compareListingIds, toggleCompareListing: (id) => setCompareListingIds(p => p.includes(id) ? p.filter(i => i !== id) : p.length < 3 ? [...p, id] : p),
    isInCompare: (id) => compareListingIds.includes(id), clearCompare: () => setCompareListingIds([]),
    createListing, updateListing, deleteListing, markAsSold, conversations, sendMessage,
    notifications, markNotificationRead: (id) => notificationService.markRead(id).then(() => fetchData()),
    markAllNotificationsRead: () => Promise.all(notifications.map(n => notificationService.markRead(n.id))).then(() => fetchData()),
    clearNotification: (id) => notificationService.clear(id).then(() => fetchData()),
    addNotification, broadcastMassNotification, dispatchPromotionalEmailDigest,
    passwordRequests, verificationRequests, promotionPaymentRequests, announcements,
    reports, disputeCases, auditLogs, recentDeals, intrusionLogs, searchAlerts,
    reviews, buyerRequests, wallet, transactions, loading, isSyncing, lastSyncTime, syncDatabase: fetchData, error
  ]);