// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qldwkoapgenmohuqnidr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsZHdrb2FwZ2VubW9odXFuaWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ2NDc4MDUsImV4cCI6MjEwMDIyMzgwNX0.sHM7fxGLqDgGFe6QwjSCv-U1YcZgWq_EUlP5gSdHwfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);