// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://eliwjdafimaugnwvadlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_h4te__ofhyf2Ou5uALG-Sw_lsKjDQR7";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);